Stabilize lucene indexing
infonova/gitblit pull request #8
Opened 2018-01-23 13:01 UTC by feuer93

*) Prevent Lucene thread scheduler from dying
*) Resume indexing on repositories even if an error occurs
*) Remove System.gc() from Lucene service

Issue: INFRABRBA-5062

2018-01-25 13:41 UTC, ederst requested changes

2018-01-25 13:41 UTC, ederst commented on src/main/java/com/gitblit/service/LuceneService.java
> +						repository.close();
Please coloe `repository` in a final block.

2018-01-25 13:41 UTC, ederst commented on src/main/java/com/gitblit/service/LuceneService.java
> +			logger.error("Error while indexing lucene!", e);
Maybe better: "General error while indexing lucene:" (use ":" or no punctuation)

2018-01-25 13:41 UTC, ederst commented on src/main/java/com/gitblit/service/LuceneService.java
> +					logger.error("Error while indexing lucene on repository " + repositoryName, e);
Maybe better: "Error while indexing lucene for repository"

2018-01-26 11:28 UTC, feuer93 commented
Hi @ederst !
I have updated my commit... please review.

2018-01-29 08:06 UTC, feuer93 commented
@ederst, schaut gut aus!

2018-01-29 08:06 UTC, aprattes reviewed
looks great!

2018-01-29 09:13 UTC, ederst approved these changes

2018-01-29 10:53 UTC, merged